#!/usr/bin/env tcsh
#
# smurf-train.sh - generates a hidden Markov model for use with smurf
# Copyright 2010 Jeffrey Finkelstein
# 
# This file is part of smurf.
#
# smurf is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 2 of the License, or (at your option) any later
# version.
#
# smurf is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# smurf.  If not, see <http://www.gnu.org/licenses/>.

set STATUS_ARGS=4

if ($# != 2 && $# != 3) then
    echo "Usage: $0 <PDBlistfile> <HMMfile> [Matt-outputdir]"
    exit $STATUS_ARGS
endif

# prefix for temporary files generated by Matt
set PREFIX=/tmp/smurf/mattAlignment$!
if ($?3) then
    set PREFIX=$3/mattAlignment$!

# get file names from command line arguments
set PDBLISTFILE=$1
set HMMFILE=$2

# train the alignment on the file containing a list of PDB files on each line
echo "[DEBUG] Running Matt..."
matt -o $PREFIX -L $PDBLISTFILE

if ($status != 0) then
    echo "[DEBUG] matt exited with status $status"
    exit $status
endif

# add some beta strand information
echo "[DEBUG] Running smurf-preparse..."
smurf-preparse $PREFIX

if ($status != 0) then
    echo "[DEBUG] smurf-preparse exited with status $status"
    exit $status
endif

# build the hidden Markov model
echo "[DEBUG] Running hmmbuild..."
smurf-hmmbuild $HMMFILE $PREFIX.ssi

exit $status
